<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>meanFilterInTime</name>
		<ret_bitwidth>32</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>2</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>x_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>op.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>reset</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>reset</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>42</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_3">
				<Value>
					<Obj>
						<type>0</type>
						<id>4</id>
						<name>reset_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>reset</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>51</item>
					<item>52</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>5</id>
						<name>x_V_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>op.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>54</item>
					<item>55</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>7</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>166</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>166</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>56</item>
					<item>57</item>
					<item>58</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>9</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>172</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>172</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>60</item>
					<item>64</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>10</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>172</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>172</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>65</item>
					<item>68</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>11</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>172</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>172</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>69</item>
					<item>72</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>12</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>172</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>172</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>73</item>
					<item>76</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>13</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>172</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>172</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>77</item>
					<item>80</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>14</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>172</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>172</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>81</item>
					<item>84</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>15</id>
						<name></name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>85</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>17</id>
						<name>aux_array_V_load</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>87</item>
					<item>192</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>18</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>88</item>
					<item>91</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name>tmp_31_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>92</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>20</id>
						<name>aux_array_V_load_1</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>94</item>
					<item>193</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>21</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>95</item>
					<item>97</item>
					<item>191</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>22</id>
						<name>tmp_31_1_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>181</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>181</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>98</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>23</id>
						<name>aux_array_V_load_2</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>100</item>
					<item>194</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>24</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>101</item>
					<item>103</item>
					<item>190</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>25</id>
						<name>tmp_31_2_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>181</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>181</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>104</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>26</id>
						<name>aux_array_V_load_3</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>106</item>
					<item>195</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>27</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>107</item>
					<item>109</item>
					<item>189</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_24">
				<Value>
					<Obj>
						<type>0</type>
						<id>28</id>
						<name>tmp_31_3_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>181</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>181</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>110</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_25">
				<Value>
					<Obj>
						<type>0</type>
						<id>29</id>
						<name>aux_array_V_load_4</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>112</item>
					<item>196</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_26">
				<Value>
					<Obj>
						<type>0</type>
						<id>30</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>113</item>
					<item>115</item>
					<item>188</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_27">
				<Value>
					<Obj>
						<type>0</type>
						<id>31</id>
						<name>tmp_31_4_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>181</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>181</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>116</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_28">
				<Value>
					<Obj>
						<type>0</type>
						<id>32</id>
						<name>aux_array_V_load_5</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>118</item>
					<item>197</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_29">
				<Value>
					<Obj>
						<type>0</type>
						<id>33</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>119</item>
					<item>121</item>
					<item>187</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_30">
				<Value>
					<Obj>
						<type>0</type>
						<id>34</id>
						<name>tmp_31_5_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>181</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>181</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>122</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_31">
				<Value>
					<Obj>
						<type>0</type>
						<id>35</id>
						<name>aux_array_V_load_6</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>125</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_32">
				<Value>
					<Obj>
						<type>0</type>
						<id>36</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>180</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>180</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>126</item>
					<item>128</item>
					<item>186</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_33">
				<Value>
					<Obj>
						<type>0</type>
						<id>37</id>
						<name>tmp_31_6_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>181</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>181</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>129</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_34">
				<Value>
					<Obj>
						<type>0</type>
						<id>38</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>183</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>183</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>130</item>
					<item>132</item>
					<item>185</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_35">
				<Value>
					<Obj>
						<type>0</type>
						<id>39</id>
						<name>tmp_cast_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>133</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_36">
				<Value>
					<Obj>
						<type>0</type>
						<id>40</id>
						<name>tmp1</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>134</item>
					<item>135</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_37">
				<Value>
					<Obj>
						<type>0</type>
						<id>41</id>
						<name>tmp2</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>136</item>
					<item>137</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_38">
				<Value>
					<Obj>
						<type>0</type>
						<id>42</id>
						<name>tmp</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>138</item>
					<item>139</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_39">
				<Value>
					<Obj>
						<type>0</type>
						<id>43</id>
						<name>tmp4</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>140</item>
					<item>141</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_40">
				<Value>
					<Obj>
						<type>0</type>
						<id>44</id>
						<name>tmp5</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>142</item>
					<item>143</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_41">
				<Value>
					<Obj>
						<type>0</type>
						<id>45</id>
						<name>tmp3</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>144</item>
					<item>145</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_42">
				<Value>
					<Obj>
						<type>0</type>
						<id>46</id>
						<name>p_Val2_i</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>184</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>184</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>33</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>146</item>
					<item>147</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_43">
				<Value>
					<Obj>
						<type>0</type>
						<id>47</id>
						<name>y_0_V_write_assign</name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>187</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>187</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>y[0].V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>149</item>
					<item>150</item>
					<item>152</item>
					<item>154</item>
				</oprand_edges>
				<opcode>partselect</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_44">
				<Value>
					<Obj>
						<type>0</type>
						<id>48</id>
						<name></name>
						<fileName>axi_algorithm.cpp</fileName>
						<fileDirectory>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</fileDirectory>
						<lineNumber>187</lineNumber>
						<contextFuncName>meanFilterInTime</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Raul\Documents\thesis_rep\thesis\HLS\ALGORITMO_BARRIDO</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>axi_algorithm.cpp</first>
											<second>meanFilterInTime</second>
										</first>
										<second>187</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>155</item>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>11</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_45">
				<Value>
					<Obj>
						<type>2</type>
						<id>59</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_46">
				<Value>
					<Obj>
						<type>2</type>
						<id>62</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_47">
				<Value>
					<Obj>
						<type>2</type>
						<id>66</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>2</content>
			</item>
			<item class_id_reference="16" object_id="_48">
				<Value>
					<Obj>
						<type>2</type>
						<id>70</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>3</content>
			</item>
			<item class_id_reference="16" object_id="_49">
				<Value>
					<Obj>
						<type>2</type>
						<id>74</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>4</content>
			</item>
			<item class_id_reference="16" object_id="_50">
				<Value>
					<Obj>
						<type>2</type>
						<id>78</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>5</content>
			</item>
			<item class_id_reference="16" object_id="_51">
				<Value>
					<Obj>
						<type>2</type>
						<id>82</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>6</content>
			</item>
			<item class_id_reference="16" object_id="_52">
				<Value>
					<Obj>
						<type>2</type>
						<id>89</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_53">
				<Value>
					<Obj>
						<type>2</type>
						<id>123</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>3</const_type>
				<content>7</content>
			</item>
			<item class_id_reference="16" object_id="_54">
				<Value>
					<Obj>
						<type>2</type>
						<id>151</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_55">
				<Value>
					<Obj>
						<type>2</type>
						<id>153</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>32</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_56">
				<Obj>
					<type>3</type>
					<id>8</id>
					<name>entry</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>3</count>
					<item_version>0</item_version>
					<item>4</item>
					<item>5</item>
					<item>7</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_57">
				<Obj>
					<type>3</type>
					<id>16</id>
					<name>.preheader.i</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>7</count>
					<item_version>0</item_version>
					<item>9</item>
					<item>10</item>
					<item>11</item>
					<item>12</item>
					<item>13</item>
					<item>14</item>
					<item>15</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_58">
				<Obj>
					<type>3</type>
					<id>49</id>
					<name>meanFilterInTime.exit</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>32</count>
					<item_version>0</item_version>
					<item>17</item>
					<item>18</item>
					<item>19</item>
					<item>20</item>
					<item>21</item>
					<item>22</item>
					<item>23</item>
					<item>24</item>
					<item>25</item>
					<item>26</item>
					<item>27</item>
					<item>28</item>
					<item>29</item>
					<item>30</item>
					<item>31</item>
					<item>32</item>
					<item>33</item>
					<item>34</item>
					<item>35</item>
					<item>36</item>
					<item>37</item>
					<item>38</item>
					<item>39</item>
					<item>40</item>
					<item>41</item>
					<item>42</item>
					<item>43</item>
					<item>44</item>
					<item>45</item>
					<item>46</item>
					<item>47</item>
					<item>48</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>104</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_59">
				<id>52</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>4</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_60">
				<id>55</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>5</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_61">
				<id>56</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>7</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_62">
				<id>57</id>
				<edge_type>2</edge_type>
				<source_obj>49</source_obj>
				<sink_obj>7</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_63">
				<id>58</id>
				<edge_type>2</edge_type>
				<source_obj>16</source_obj>
				<sink_obj>7</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>60</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>63</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>62</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>64</id>
				<edge_type>1</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>65</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>10</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>67</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>66</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>68</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>10</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>69</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>11</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>71</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>70</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>72</id>
				<edge_type>1</edge_type>
				<source_obj>70</source_obj>
				<sink_obj>11</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>73</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>12</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>75</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>74</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>76</id>
				<edge_type>1</edge_type>
				<source_obj>74</source_obj>
				<sink_obj>12</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_76">
				<id>77</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_77">
				<id>79</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>78</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_78">
				<id>80</id>
				<edge_type>1</edge_type>
				<source_obj>78</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_79">
				<id>81</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>14</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_80">
				<id>83</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>82</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_81">
				<id>84</id>
				<edge_type>1</edge_type>
				<source_obj>82</source_obj>
				<sink_obj>14</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_82">
				<id>85</id>
				<edge_type>2</edge_type>
				<source_obj>49</source_obj>
				<sink_obj>15</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_83">
				<id>86</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>62</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_84">
				<id>87</id>
				<edge_type>1</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>17</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_85">
				<id>88</id>
				<edge_type>1</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>18</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_86">
				<id>90</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>89</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_87">
				<id>91</id>
				<edge_type>1</edge_type>
				<source_obj>89</source_obj>
				<sink_obj>18</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_88">
				<id>92</id>
				<edge_type>1</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_89">
				<id>93</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>66</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_90">
				<id>94</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>20</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_91">
				<id>95</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>21</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_92">
				<id>96</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>62</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_93">
				<id>97</id>
				<edge_type>1</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>21</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_94">
				<id>98</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>22</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_95">
				<id>99</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>70</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_96">
				<id>100</id>
				<edge_type>1</edge_type>
				<source_obj>70</source_obj>
				<sink_obj>23</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_97">
				<id>101</id>
				<edge_type>1</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>24</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_98">
				<id>102</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>66</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_99">
				<id>103</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>24</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_100">
				<id>104</id>
				<edge_type>1</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>25</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_101">
				<id>105</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>74</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_102">
				<id>106</id>
				<edge_type>1</edge_type>
				<source_obj>74</source_obj>
				<sink_obj>26</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_103">
				<id>107</id>
				<edge_type>1</edge_type>
				<source_obj>26</source_obj>
				<sink_obj>27</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_104">
				<id>108</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>70</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_105">
				<id>109</id>
				<edge_type>1</edge_type>
				<source_obj>70</source_obj>
				<sink_obj>27</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_106">
				<id>110</id>
				<edge_type>1</edge_type>
				<source_obj>26</source_obj>
				<sink_obj>28</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_107">
				<id>111</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>78</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_108">
				<id>112</id>
				<edge_type>1</edge_type>
				<source_obj>78</source_obj>
				<sink_obj>29</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_109">
				<id>113</id>
				<edge_type>1</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>30</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_110">
				<id>114</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>74</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_111">
				<id>115</id>
				<edge_type>1</edge_type>
				<source_obj>74</source_obj>
				<sink_obj>30</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_112">
				<id>116</id>
				<edge_type>1</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>31</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_113">
				<id>117</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>82</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_114">
				<id>118</id>
				<edge_type>1</edge_type>
				<source_obj>82</source_obj>
				<sink_obj>32</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_115">
				<id>119</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>33</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_116">
				<id>120</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>78</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_117">
				<id>121</id>
				<edge_type>1</edge_type>
				<source_obj>78</source_obj>
				<sink_obj>33</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_118">
				<id>122</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>34</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_119">
				<id>124</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>123</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_120">
				<id>125</id>
				<edge_type>1</edge_type>
				<source_obj>123</source_obj>
				<sink_obj>35</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_121">
				<id>126</id>
				<edge_type>1</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>36</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_122">
				<id>127</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>82</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_123">
				<id>128</id>
				<edge_type>1</edge_type>
				<source_obj>82</source_obj>
				<sink_obj>36</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_124">
				<id>129</id>
				<edge_type>1</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_125">
				<id>130</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>38</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_126">
				<id>131</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>123</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_127">
				<id>132</id>
				<edge_type>1</edge_type>
				<source_obj>123</source_obj>
				<sink_obj>38</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_128">
				<id>133</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>39</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_129">
				<id>134</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_130">
				<id>135</id>
				<edge_type>1</edge_type>
				<source_obj>22</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_131">
				<id>136</id>
				<edge_type>1</edge_type>
				<source_obj>25</source_obj>
				<sink_obj>41</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_132">
				<id>137</id>
				<edge_type>1</edge_type>
				<source_obj>28</source_obj>
				<sink_obj>41</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_133">
				<id>138</id>
				<edge_type>1</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_134">
				<id>139</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_135">
				<id>140</id>
				<edge_type>1</edge_type>
				<source_obj>31</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_136">
				<id>141</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_137">
				<id>142</id>
				<edge_type>1</edge_type>
				<source_obj>37</source_obj>
				<sink_obj>44</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_138">
				<id>143</id>
				<edge_type>1</edge_type>
				<source_obj>39</source_obj>
				<sink_obj>44</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_139">
				<id>144</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>45</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_140">
				<id>145</id>
				<edge_type>1</edge_type>
				<source_obj>43</source_obj>
				<sink_obj>45</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_141">
				<id>146</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_142">
				<id>147</id>
				<edge_type>1</edge_type>
				<source_obj>42</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_143">
				<id>150</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_144">
				<id>152</id>
				<edge_type>1</edge_type>
				<source_obj>151</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_145">
				<id>154</id>
				<edge_type>1</edge_type>
				<source_obj>153</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_146">
				<id>155</id>
				<edge_type>1</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>48</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_147">
				<id>182</id>
				<edge_type>2</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>16</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_148">
				<id>183</id>
				<edge_type>2</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_149">
				<id>184</id>
				<edge_type>2</edge_type>
				<source_obj>16</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_150">
				<id>185</id>
				<edge_type>4</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>38</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_151">
				<id>186</id>
				<edge_type>4</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>36</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_152">
				<id>187</id>
				<edge_type>4</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>33</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_153">
				<id>188</id>
				<edge_type>4</edge_type>
				<source_obj>26</source_obj>
				<sink_obj>30</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_154">
				<id>189</id>
				<edge_type>4</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>27</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_155">
				<id>190</id>
				<edge_type>4</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>24</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_156">
				<id>191</id>
				<edge_type>4</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>21</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_157">
				<id>192</id>
				<edge_type>4</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>17</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_158">
				<id>193</id>
				<edge_type>4</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>20</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_159">
				<id>194</id>
				<edge_type>4</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>23</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_160">
				<id>195</id>
				<edge_type>4</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>26</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_161">
				<id>196</id>
				<edge_type>4</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>29</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_162">
				<id>197</id>
				<edge_type>4</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>32</sink_obj>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_163">
			<mId>1</mId>
			<mTag>meanFilterInTime</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>3</count>
				<item_version>0</item_version>
				<item>8</item>
				<item>16</item>
				<item>49</item>
			</basic_blocks>
			<mII>14</mII>
			<mDepth>14</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>13</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>42</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>4</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>5</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>7</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>9</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>10</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>11</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>12</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>13</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>14</first>
			<second>
				<first>5</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>15</first>
			<second>
				<first>13</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>17</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>18</first>
			<second>
				<first>7</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>19</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>2</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>21</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>22</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>3</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>24</first>
			<second>
				<first>9</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>25</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>26</first>
			<second>
				<first>4</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>27</first>
			<second>
				<first>10</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>28</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>29</first>
			<second>
				<first>5</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>11</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>31</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>32</first>
			<second>
				<first>6</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>33</first>
			<second>
				<first>12</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>34</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>35</first>
			<second>
				<first>0</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>36</first>
			<second>
				<first>13</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>37</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>38</first>
			<second>
				<first>6</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>39</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>40</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>41</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>42</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>43</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>44</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>45</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>46</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>47</first>
			<second>
				<first>8</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>48</first>
			<second>
				<first>13</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>3</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>8</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>16</first>
			<second>
				<first>0</first>
				<second>13</second>
			</second>
		</item>
		<item>
			<first>49</first>
			<second>
				<first>0</first>
				<second>13</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="33" tracking_level="1" version="0" object_id="_164">
			<region_name>meanFilterInTime</region_name>
			<basic_blocks>
				<count>3</count>
				<item_version>0</item_version>
				<item>8</item>
				<item>16</item>
				<item>49</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>14</interval>
			<pipe_depth>14</pipe_depth>
		</item>
	</regions>
	<dp_fu_nodes class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

