// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _read_data_HH_
#define _read_data_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct read_data : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > input_AX_ALG_TDATA;
    sc_in< sc_logic > input_AX_ALG_TVALID;
    sc_out< sc_logic > input_AX_ALG_TREADY;
    sc_in< sc_lv<4> > input_AX_ALG_TKEEP;
    sc_in< sc_lv<4> > input_AX_ALG_TSTRB;
    sc_in< sc_lv<4> > input_AX_ALG_TUSER;
    sc_in< sc_lv<1> > input_AX_ALG_TLAST;
    sc_in< sc_lv<5> > input_AX_ALG_TID;
    sc_in< sc_lv<5> > input_AX_ALG_TDEST;
    sc_out< sc_lv<32> > ap_return;
    sc_out< sc_logic > input_AX_ALG_TDATA_blk_n;


    // Module declarations
    read_data(sc_module_name name);
    SC_HAS_PROCESS(read_data);

    ~read_data();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_input_AX_ALG_TDATA_blk_n();
    void thread_input_AX_ALG_TREADY();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
