-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity axi_algorithm is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_AX_ALG_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_AX_ALG_TVALID : IN STD_LOGIC;
    input_AX_ALG_TREADY : OUT STD_LOGIC;
    input_AX_ALG_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    input_AX_ALG_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    input_AX_ALG_TUSER : IN STD_LOGIC_VECTOR (3 downto 0);
    input_AX_ALG_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_AX_ALG_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    input_AX_ALG_TDEST : IN STD_LOGIC_VECTOR (4 downto 0);
    output_AX_ALG_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_AX_ALG_TVALID : OUT STD_LOGIC;
    output_AX_ALG_TREADY : IN STD_LOGIC;
    output_AX_ALG_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_AX_ALG_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_AX_ALG_TUSER : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_AX_ALG_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_AX_ALG_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    output_AX_ALG_TDEST : OUT STD_LOGIC_VECTOR (4 downto 0);
    full_fifo : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of axi_algorithm is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "axi_algorithm,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.107000,HLS_SYN_LAT=19983,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=2048,HLS_SYN_FF=161222,HLS_SYN_LUT=63535}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal input_AX_ALG_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal input_AX_ALG_data_V_0_vld_in : STD_LOGIC;
    signal input_AX_ALG_data_V_0_vld_out : STD_LOGIC;
    signal input_AX_ALG_data_V_0_ack_in : STD_LOGIC;
    signal input_AX_ALG_data_V_0_ack_out : STD_LOGIC;
    signal input_AX_ALG_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal input_AX_ALG_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal input_AX_ALG_data_V_0_sel_rd : STD_LOGIC := '0';
    signal input_AX_ALG_data_V_0_sel_wr : STD_LOGIC := '0';
    signal input_AX_ALG_data_V_0_sel : STD_LOGIC;
    signal input_AX_ALG_data_V_0_load_A : STD_LOGIC;
    signal input_AX_ALG_data_V_0_load_B : STD_LOGIC;
    signal input_AX_ALG_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_AX_ALG_data_V_0_state_cmp_full : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_keep_V_0_vld_in : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_vld_out : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_ack_in : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_ack_out : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_keep_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_keep_V_0_sel_rd : STD_LOGIC := '0';
    signal input_AX_ALG_keep_V_0_sel_wr : STD_LOGIC := '0';
    signal input_AX_ALG_keep_V_0_sel : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_load_A : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_load_B : STD_LOGIC;
    signal input_AX_ALG_keep_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_AX_ALG_keep_V_0_state_cmp_full : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_strb_V_0_vld_in : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_vld_out : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_ack_in : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_ack_out : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_strb_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_strb_V_0_sel_rd : STD_LOGIC := '0';
    signal input_AX_ALG_strb_V_0_sel_wr : STD_LOGIC := '0';
    signal input_AX_ALG_strb_V_0_sel : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_load_A : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_load_B : STD_LOGIC;
    signal input_AX_ALG_strb_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_AX_ALG_strb_V_0_state_cmp_full : STD_LOGIC;
    signal input_AX_ALG_user_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_user_V_0_vld_in : STD_LOGIC;
    signal input_AX_ALG_user_V_0_vld_out : STD_LOGIC;
    signal input_AX_ALG_user_V_0_ack_in : STD_LOGIC;
    signal input_AX_ALG_user_V_0_ack_out : STD_LOGIC;
    signal input_AX_ALG_user_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_user_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal input_AX_ALG_user_V_0_sel_rd : STD_LOGIC := '0';
    signal input_AX_ALG_user_V_0_sel_wr : STD_LOGIC := '0';
    signal input_AX_ALG_user_V_0_sel : STD_LOGIC;
    signal input_AX_ALG_user_V_0_load_A : STD_LOGIC;
    signal input_AX_ALG_user_V_0_load_B : STD_LOGIC;
    signal input_AX_ALG_user_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_AX_ALG_user_V_0_state_cmp_full : STD_LOGIC;
    signal input_AX_ALG_last_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal input_AX_ALG_last_V_0_vld_in : STD_LOGIC;
    signal input_AX_ALG_last_V_0_vld_out : STD_LOGIC;
    signal input_AX_ALG_last_V_0_ack_in : STD_LOGIC;
    signal input_AX_ALG_last_V_0_ack_out : STD_LOGIC;
    signal input_AX_ALG_last_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal input_AX_ALG_last_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal input_AX_ALG_last_V_0_sel_rd : STD_LOGIC := '0';
    signal input_AX_ALG_last_V_0_sel_wr : STD_LOGIC := '0';
    signal input_AX_ALG_last_V_0_sel : STD_LOGIC;
    signal input_AX_ALG_last_V_0_load_A : STD_LOGIC;
    signal input_AX_ALG_last_V_0_load_B : STD_LOGIC;
    signal input_AX_ALG_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_AX_ALG_last_V_0_state_cmp_full : STD_LOGIC;
    signal input_AX_ALG_id_V_0_data_out : STD_LOGIC_VECTOR (4 downto 0);
    signal input_AX_ALG_id_V_0_vld_in : STD_LOGIC;
    signal input_AX_ALG_id_V_0_vld_out : STD_LOGIC;
    signal input_AX_ALG_id_V_0_ack_in : STD_LOGIC;
    signal input_AX_ALG_id_V_0_ack_out : STD_LOGIC;
    signal input_AX_ALG_id_V_0_payload_A : STD_LOGIC_VECTOR (4 downto 0);
    signal input_AX_ALG_id_V_0_payload_B : STD_LOGIC_VECTOR (4 downto 0);
    signal input_AX_ALG_id_V_0_sel_rd : STD_LOGIC := '0';
    signal input_AX_ALG_id_V_0_sel_wr : STD_LOGIC := '0';
    signal input_AX_ALG_id_V_0_sel : STD_LOGIC;
    signal input_AX_ALG_id_V_0_load_A : STD_LOGIC;
    signal input_AX_ALG_id_V_0_load_B : STD_LOGIC;
    signal input_AX_ALG_id_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_AX_ALG_id_V_0_state_cmp_full : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_data_out : STD_LOGIC_VECTOR (4 downto 0);
    signal input_AX_ALG_dest_V_0_vld_in : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_vld_out : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_ack_in : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_ack_out : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_payload_A : STD_LOGIC_VECTOR (4 downto 0);
    signal input_AX_ALG_dest_V_0_payload_B : STD_LOGIC_VECTOR (4 downto 0);
    signal input_AX_ALG_dest_V_0_sel_rd : STD_LOGIC := '0';
    signal input_AX_ALG_dest_V_0_sel_wr : STD_LOGIC := '0';
    signal input_AX_ALG_dest_V_0_sel : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_load_A : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_load_B : STD_LOGIC;
    signal input_AX_ALG_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_AX_ALG_dest_V_0_state_cmp_full : STD_LOGIC;
    signal output_AX_ALG_data_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal output_AX_ALG_data_V_1_vld_in : STD_LOGIC;
    signal output_AX_ALG_data_V_1_vld_out : STD_LOGIC;
    signal output_AX_ALG_data_V_1_ack_in : STD_LOGIC;
    signal output_AX_ALG_data_V_1_ack_out : STD_LOGIC;
    signal output_AX_ALG_data_V_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal output_AX_ALG_data_V_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal output_AX_ALG_data_V_1_sel_rd : STD_LOGIC := '0';
    signal output_AX_ALG_data_V_1_sel_wr : STD_LOGIC := '0';
    signal output_AX_ALG_data_V_1_sel : STD_LOGIC;
    signal output_AX_ALG_data_V_1_load_A : STD_LOGIC;
    signal output_AX_ALG_data_V_1_load_B : STD_LOGIC;
    signal output_AX_ALG_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_AX_ALG_data_V_1_state_cmp_full : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_keep_V_1_vld_in : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_vld_out : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_ack_in : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_ack_out : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_keep_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal output_AX_ALG_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal output_AX_ALG_keep_V_1_sel : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_load_A : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_load_B : STD_LOGIC;
    signal output_AX_ALG_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_AX_ALG_keep_V_1_state_cmp_full : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_strb_V_1_vld_in : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_vld_out : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_ack_in : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_ack_out : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_strb_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal output_AX_ALG_strb_V_1_sel_wr : STD_LOGIC := '0';
    signal output_AX_ALG_strb_V_1_sel : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_load_A : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_load_B : STD_LOGIC;
    signal output_AX_ALG_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_AX_ALG_strb_V_1_state_cmp_full : STD_LOGIC;
    signal output_AX_ALG_user_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_user_V_1_vld_in : STD_LOGIC;
    signal output_AX_ALG_user_V_1_vld_out : STD_LOGIC;
    signal output_AX_ALG_user_V_1_ack_in : STD_LOGIC;
    signal output_AX_ALG_user_V_1_ack_out : STD_LOGIC;
    signal output_AX_ALG_user_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_user_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal output_AX_ALG_user_V_1_sel_rd : STD_LOGIC := '0';
    signal output_AX_ALG_user_V_1_sel_wr : STD_LOGIC := '0';
    signal output_AX_ALG_user_V_1_sel : STD_LOGIC;
    signal output_AX_ALG_user_V_1_load_A : STD_LOGIC;
    signal output_AX_ALG_user_V_1_load_B : STD_LOGIC;
    signal output_AX_ALG_user_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_AX_ALG_user_V_1_state_cmp_full : STD_LOGIC;
    signal output_AX_ALG_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal output_AX_ALG_last_V_1_vld_in : STD_LOGIC;
    signal output_AX_ALG_last_V_1_vld_out : STD_LOGIC;
    signal output_AX_ALG_last_V_1_ack_in : STD_LOGIC;
    signal output_AX_ALG_last_V_1_ack_out : STD_LOGIC;
    signal output_AX_ALG_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal output_AX_ALG_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal output_AX_ALG_last_V_1_sel_rd : STD_LOGIC := '0';
    signal output_AX_ALG_last_V_1_sel_wr : STD_LOGIC := '0';
    signal output_AX_ALG_last_V_1_sel : STD_LOGIC;
    signal output_AX_ALG_last_V_1_load_A : STD_LOGIC;
    signal output_AX_ALG_last_V_1_load_B : STD_LOGIC;
    signal output_AX_ALG_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_AX_ALG_last_V_1_state_cmp_full : STD_LOGIC;
    signal output_AX_ALG_id_V_1_data_out : STD_LOGIC_VECTOR (4 downto 0);
    signal output_AX_ALG_id_V_1_vld_in : STD_LOGIC;
    signal output_AX_ALG_id_V_1_vld_out : STD_LOGIC;
    signal output_AX_ALG_id_V_1_ack_in : STD_LOGIC;
    signal output_AX_ALG_id_V_1_ack_out : STD_LOGIC;
    signal output_AX_ALG_id_V_1_payload_A : STD_LOGIC_VECTOR (4 downto 0);
    signal output_AX_ALG_id_V_1_payload_B : STD_LOGIC_VECTOR (4 downto 0);
    signal output_AX_ALG_id_V_1_sel_rd : STD_LOGIC := '0';
    signal output_AX_ALG_id_V_1_sel_wr : STD_LOGIC := '0';
    signal output_AX_ALG_id_V_1_sel : STD_LOGIC;
    signal output_AX_ALG_id_V_1_load_A : STD_LOGIC;
    signal output_AX_ALG_id_V_1_load_B : STD_LOGIC;
    signal output_AX_ALG_id_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_AX_ALG_id_V_1_state_cmp_full : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_data_out : STD_LOGIC_VECTOR (4 downto 0);
    signal output_AX_ALG_dest_V_1_vld_in : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_vld_out : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_ack_in : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_ack_out : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_payload_A : STD_LOGIC_VECTOR (4 downto 0);
    signal output_AX_ALG_dest_V_1_payload_B : STD_LOGIC_VECTOR (4 downto 0);
    signal output_AX_ALG_dest_V_1_sel_rd : STD_LOGIC := '0';
    signal output_AX_ALG_dest_V_1_sel_wr : STD_LOGIC := '0';
    signal output_AX_ALG_dest_V_1_sel : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_load_A : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_load_B : STD_LOGIC;
    signal output_AX_ALG_dest_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_AX_ALG_dest_V_1_state_cmp_full : STD_LOGIC;
    signal buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n : STD_LOGIC;
    signal input_AX_ALG_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_Val2_1_fu_127_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_1_reg_138 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_sweep_algorithm_DECM_fu_76_ap_start : STD_LOGIC;
    signal grp_sweep_algorithm_DECM_fu_76_ap_done : STD_LOGIC;
    signal grp_sweep_algorithm_DECM_fu_76_ap_idle : STD_LOGIC;
    signal grp_sweep_algorithm_DECM_fu_76_ap_ready : STD_LOGIC;
    signal grp_write_data_fu_89_ap_start : STD_LOGIC;
    signal grp_write_data_fu_89_ap_done : STD_LOGIC;
    signal grp_write_data_fu_89_ap_idle : STD_LOGIC;
    signal grp_write_data_fu_89_ap_ready : STD_LOGIC;
    signal grp_write_data_fu_89_output_AX_ALG_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_data_fu_89_output_AX_ALG_TVALID : STD_LOGIC;
    signal grp_write_data_fu_89_output_AX_ALG_TREADY : STD_LOGIC;
    signal grp_write_data_fu_89_output_AX_ALG_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_data_fu_89_output_AX_ALG_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_data_fu_89_output_AX_ALG_TUSER : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_data_fu_89_output_AX_ALG_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_data_fu_89_output_AX_ALG_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_write_data_fu_89_output_AX_ALG_TDEST : STD_LOGIC_VECTOR (4 downto 0);
    signal buf_Tj_in_0_V_read_data_fu_109_ap_start : STD_LOGIC;
    signal buf_Tj_in_0_V_read_data_fu_109_ap_done : STD_LOGIC;
    signal buf_Tj_in_0_V_read_data_fu_109_ap_idle : STD_LOGIC;
    signal buf_Tj_in_0_V_read_data_fu_109_ap_ready : STD_LOGIC;
    signal buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TVALID : STD_LOGIC;
    signal buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY : STD_LOGIC;
    signal buf_Tj_in_0_V_read_data_fu_109_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_grp_sweep_algorithm_DECM_fu_76_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_reg_grp_write_data_fu_89_ap_start : STD_LOGIC := '0';
    signal tmp_s_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_state5 : BOOLEAN;

    component sweep_algorithm_DECM IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inputVal_V : IN STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component write_data IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_0_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
        output_AX_ALG_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        output_AX_ALG_TVALID : OUT STD_LOGIC;
        output_AX_ALG_TREADY : IN STD_LOGIC;
        output_AX_ALG_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_AX_ALG_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_AX_ALG_TUSER : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_AX_ALG_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_AX_ALG_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        output_AX_ALG_TDEST : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component read_data IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_AX_ALG_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        input_AX_ALG_TVALID : IN STD_LOGIC;
        input_AX_ALG_TREADY : OUT STD_LOGIC;
        input_AX_ALG_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        input_AX_ALG_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        input_AX_ALG_TUSER : IN STD_LOGIC_VECTOR (3 downto 0);
        input_AX_ALG_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_AX_ALG_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        input_AX_ALG_TDEST : IN STD_LOGIC_VECTOR (4 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_AX_ALG_TDATA_blk_n : OUT STD_LOGIC );
    end component;



begin
    grp_sweep_algorithm_DECM_fu_76 : component sweep_algorithm_DECM
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sweep_algorithm_DECM_fu_76_ap_start,
        ap_done => grp_sweep_algorithm_DECM_fu_76_ap_done,
        ap_idle => grp_sweep_algorithm_DECM_fu_76_ap_idle,
        ap_ready => grp_sweep_algorithm_DECM_fu_76_ap_ready,
        inputVal_V => p_Val2_1_reg_138);

    grp_write_data_fu_89 : component write_data
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_write_data_fu_89_ap_start,
        ap_done => grp_write_data_fu_89_ap_done,
        ap_idle => grp_write_data_fu_89_ap_idle,
        ap_ready => grp_write_data_fu_89_ap_ready,
        buf_0_V_read => ap_const_lv1_0,
        output_AX_ALG_TDATA => grp_write_data_fu_89_output_AX_ALG_TDATA,
        output_AX_ALG_TVALID => grp_write_data_fu_89_output_AX_ALG_TVALID,
        output_AX_ALG_TREADY => grp_write_data_fu_89_output_AX_ALG_TREADY,
        output_AX_ALG_TKEEP => grp_write_data_fu_89_output_AX_ALG_TKEEP,
        output_AX_ALG_TSTRB => grp_write_data_fu_89_output_AX_ALG_TSTRB,
        output_AX_ALG_TUSER => grp_write_data_fu_89_output_AX_ALG_TUSER,
        output_AX_ALG_TLAST => grp_write_data_fu_89_output_AX_ALG_TLAST,
        output_AX_ALG_TID => grp_write_data_fu_89_output_AX_ALG_TID,
        output_AX_ALG_TDEST => grp_write_data_fu_89_output_AX_ALG_TDEST);

    buf_Tj_in_0_V_read_data_fu_109 : component read_data
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => buf_Tj_in_0_V_read_data_fu_109_ap_start,
        ap_done => buf_Tj_in_0_V_read_data_fu_109_ap_done,
        ap_idle => buf_Tj_in_0_V_read_data_fu_109_ap_idle,
        ap_ready => buf_Tj_in_0_V_read_data_fu_109_ap_ready,
        input_AX_ALG_TDATA => input_AX_ALG_data_V_0_data_out,
        input_AX_ALG_TVALID => buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TVALID,
        input_AX_ALG_TREADY => buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY,
        input_AX_ALG_TKEEP => input_AX_ALG_keep_V_0_data_out,
        input_AX_ALG_TSTRB => input_AX_ALG_strb_V_0_data_out,
        input_AX_ALG_TUSER => input_AX_ALG_user_V_0_data_out,
        input_AX_ALG_TLAST => input_AX_ALG_last_V_0_data_out,
        input_AX_ALG_TID => input_AX_ALG_id_V_0_data_out,
        input_AX_ALG_TDEST => input_AX_ALG_dest_V_0_data_out,
        ap_return => buf_Tj_in_0_V_read_data_fu_109_ap_return,
        input_AX_ALG_TDATA_blk_n => buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_sweep_algorithm_DECM_fu_76_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_grp_sweep_algorithm_DECM_fu_76_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n = ap_const_logic_1))) then 
                    ap_reg_grp_sweep_algorithm_DECM_fu_76_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_sweep_algorithm_DECM_fu_76_ap_ready)) then 
                    ap_reg_grp_sweep_algorithm_DECM_fu_76_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_write_data_fu_89_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_grp_write_data_fu_89_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_sweep_algorithm_DECM_fu_76_ap_done = ap_const_logic_1) and (ap_const_lv1_1 = tmp_s_fu_132_p2))) then 
                    ap_reg_grp_write_data_fu_89_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_write_data_fu_89_ap_ready)) then 
                    ap_reg_grp_write_data_fu_89_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_data_V_0_ack_out) and (ap_const_logic_1 = input_AX_ALG_data_V_0_vld_out))) then 
                                        input_AX_ALG_data_V_0_sel_rd <= not(input_AX_ALG_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_data_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_data_V_0_ack_in))) then 
                                        input_AX_ALG_data_V_0_sel_wr <= not(input_AX_ALG_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = input_AX_ALG_data_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_data_V_0_ack_out) and (input_AX_ALG_data_V_0_state = ap_const_lv2_3)) or ((ap_const_logic_0 = input_AX_ALG_data_V_0_vld_in) and (input_AX_ALG_data_V_0_state = ap_const_lv2_2)))) then 
                    input_AX_ALG_data_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = input_AX_ALG_data_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_data_V_0_ack_out) and (input_AX_ALG_data_V_0_state = ap_const_lv2_3)) or ((ap_const_logic_0 = input_AX_ALG_data_V_0_ack_out) and (input_AX_ALG_data_V_0_state = ap_const_lv2_1)))) then 
                    input_AX_ALG_data_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = input_AX_ALG_data_V_0_vld_in) and (input_AX_ALG_data_V_0_state = ap_const_lv2_2)) or ((ap_const_logic_1 = input_AX_ALG_data_V_0_ack_out) and (input_AX_ALG_data_V_0_state = ap_const_lv2_1)) or ((input_AX_ALG_data_V_0_state = ap_const_lv2_3) and not(((ap_const_logic_1 = input_AX_ALG_data_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_data_V_0_ack_out))) and not(((ap_const_logic_0 = input_AX_ALG_data_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_data_V_0_ack_out)))))) then 
                    input_AX_ALG_data_V_0_state <= ap_const_lv2_3;
                else 
                    input_AX_ALG_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_dest_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_dest_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_dest_V_0_ack_out) and (ap_const_logic_1 = input_AX_ALG_dest_V_0_vld_out))) then 
                                        input_AX_ALG_dest_V_0_sel_rd <= not(input_AX_ALG_dest_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_dest_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_dest_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_dest_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_dest_V_0_ack_in))) then 
                                        input_AX_ALG_dest_V_0_sel_wr <= not(input_AX_ALG_dest_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = input_AX_ALG_dest_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_dest_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_dest_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_dest_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_dest_V_0_state)))) then 
                    input_AX_ALG_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = input_AX_ALG_dest_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_dest_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_dest_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_dest_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_dest_V_0_state)))) then 
                    input_AX_ALG_dest_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = input_AX_ALG_dest_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_dest_V_0_state)) or ((ap_const_logic_1 = input_AX_ALG_dest_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_dest_V_0_state)) or ((ap_const_lv2_3 = input_AX_ALG_dest_V_0_state) and not(((ap_const_logic_1 = input_AX_ALG_dest_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_dest_V_0_ack_out))) and not(((ap_const_logic_0 = input_AX_ALG_dest_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_dest_V_0_ack_out)))))) then 
                    input_AX_ALG_dest_V_0_state <= ap_const_lv2_3;
                else 
                    input_AX_ALG_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_id_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_id_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_id_V_0_ack_out) and (ap_const_logic_1 = input_AX_ALG_id_V_0_vld_out))) then 
                                        input_AX_ALG_id_V_0_sel_rd <= not(input_AX_ALG_id_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_id_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_id_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_id_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_id_V_0_ack_in))) then 
                                        input_AX_ALG_id_V_0_sel_wr <= not(input_AX_ALG_id_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_id_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_id_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = input_AX_ALG_id_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_id_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_id_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_id_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_id_V_0_state)))) then 
                    input_AX_ALG_id_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = input_AX_ALG_id_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_id_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_id_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_id_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_id_V_0_state)))) then 
                    input_AX_ALG_id_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = input_AX_ALG_id_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_id_V_0_state)) or ((ap_const_logic_1 = input_AX_ALG_id_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_id_V_0_state)) or ((ap_const_lv2_3 = input_AX_ALG_id_V_0_state) and not(((ap_const_logic_1 = input_AX_ALG_id_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_id_V_0_ack_out))) and not(((ap_const_logic_0 = input_AX_ALG_id_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_id_V_0_ack_out)))))) then 
                    input_AX_ALG_id_V_0_state <= ap_const_lv2_3;
                else 
                    input_AX_ALG_id_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_keep_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_keep_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_keep_V_0_ack_out) and (ap_const_logic_1 = input_AX_ALG_keep_V_0_vld_out))) then 
                                        input_AX_ALG_keep_V_0_sel_rd <= not(input_AX_ALG_keep_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_keep_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_keep_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_keep_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_keep_V_0_ack_in))) then 
                                        input_AX_ALG_keep_V_0_sel_wr <= not(input_AX_ALG_keep_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_keep_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_keep_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = input_AX_ALG_keep_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_keep_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_keep_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_keep_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_keep_V_0_state)))) then 
                    input_AX_ALG_keep_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = input_AX_ALG_keep_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_keep_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_keep_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_keep_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_keep_V_0_state)))) then 
                    input_AX_ALG_keep_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = input_AX_ALG_keep_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_keep_V_0_state)) or ((ap_const_logic_1 = input_AX_ALG_keep_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_keep_V_0_state)) or ((ap_const_lv2_3 = input_AX_ALG_keep_V_0_state) and not(((ap_const_logic_1 = input_AX_ALG_keep_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_keep_V_0_ack_out))) and not(((ap_const_logic_0 = input_AX_ALG_keep_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_keep_V_0_ack_out)))))) then 
                    input_AX_ALG_keep_V_0_state <= ap_const_lv2_3;
                else 
                    input_AX_ALG_keep_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_last_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_last_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_last_V_0_ack_out) and (ap_const_logic_1 = input_AX_ALG_last_V_0_vld_out))) then 
                                        input_AX_ALG_last_V_0_sel_rd <= not(input_AX_ALG_last_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_last_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_last_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_last_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_last_V_0_ack_in))) then 
                                        input_AX_ALG_last_V_0_sel_wr <= not(input_AX_ALG_last_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = input_AX_ALG_last_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_last_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_last_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_last_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_last_V_0_state)))) then 
                    input_AX_ALG_last_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = input_AX_ALG_last_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_last_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_last_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_last_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_last_V_0_state)))) then 
                    input_AX_ALG_last_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = input_AX_ALG_last_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_last_V_0_state)) or ((ap_const_logic_1 = input_AX_ALG_last_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_last_V_0_state)) or ((ap_const_lv2_3 = input_AX_ALG_last_V_0_state) and not(((ap_const_logic_1 = input_AX_ALG_last_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_last_V_0_ack_out))) and not(((ap_const_logic_0 = input_AX_ALG_last_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_last_V_0_ack_out)))))) then 
                    input_AX_ALG_last_V_0_state <= ap_const_lv2_3;
                else 
                    input_AX_ALG_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_strb_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_strb_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_strb_V_0_ack_out) and (ap_const_logic_1 = input_AX_ALG_strb_V_0_vld_out))) then 
                                        input_AX_ALG_strb_V_0_sel_rd <= not(input_AX_ALG_strb_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_strb_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_strb_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_strb_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_strb_V_0_ack_in))) then 
                                        input_AX_ALG_strb_V_0_sel_wr <= not(input_AX_ALG_strb_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_strb_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_strb_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = input_AX_ALG_strb_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_strb_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_strb_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_strb_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_strb_V_0_state)))) then 
                    input_AX_ALG_strb_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = input_AX_ALG_strb_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_strb_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_strb_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_strb_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_strb_V_0_state)))) then 
                    input_AX_ALG_strb_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = input_AX_ALG_strb_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_strb_V_0_state)) or ((ap_const_logic_1 = input_AX_ALG_strb_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_strb_V_0_state)) or ((ap_const_lv2_3 = input_AX_ALG_strb_V_0_state) and not(((ap_const_logic_1 = input_AX_ALG_strb_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_strb_V_0_ack_out))) and not(((ap_const_logic_0 = input_AX_ALG_strb_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_strb_V_0_ack_out)))))) then 
                    input_AX_ALG_strb_V_0_state <= ap_const_lv2_3;
                else 
                    input_AX_ALG_strb_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_user_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_user_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_user_V_0_ack_out) and (ap_const_logic_1 = input_AX_ALG_user_V_0_vld_out))) then 
                                        input_AX_ALG_user_V_0_sel_rd <= not(input_AX_ALG_user_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_user_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_user_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = input_AX_ALG_user_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_user_V_0_ack_in))) then 
                                        input_AX_ALG_user_V_0_sel_wr <= not(input_AX_ALG_user_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_AX_ALG_user_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_AX_ALG_user_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = input_AX_ALG_user_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_user_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_user_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_user_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_user_V_0_state)))) then 
                    input_AX_ALG_user_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = input_AX_ALG_user_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_user_V_0_ack_out) and (ap_const_lv2_3 = input_AX_ALG_user_V_0_state)) or ((ap_const_logic_0 = input_AX_ALG_user_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_user_V_0_state)))) then 
                    input_AX_ALG_user_V_0_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = input_AX_ALG_user_V_0_vld_in) and (ap_const_lv2_2 = input_AX_ALG_user_V_0_state)) or ((ap_const_logic_1 = input_AX_ALG_user_V_0_ack_out) and (ap_const_lv2_1 = input_AX_ALG_user_V_0_state)) or ((ap_const_lv2_3 = input_AX_ALG_user_V_0_state) and not(((ap_const_logic_1 = input_AX_ALG_user_V_0_vld_in) and (ap_const_logic_0 = input_AX_ALG_user_V_0_ack_out))) and not(((ap_const_logic_0 = input_AX_ALG_user_V_0_vld_in) and (ap_const_logic_1 = input_AX_ALG_user_V_0_ack_out)))))) then 
                    input_AX_ALG_user_V_0_state <= ap_const_lv2_3;
                else 
                    input_AX_ALG_user_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_data_V_1_ack_out) and (ap_const_logic_1 = output_AX_ALG_data_V_1_vld_out))) then 
                                        output_AX_ALG_data_V_1_sel_rd <= not(output_AX_ALG_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_data_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_data_V_1_ack_in))) then 
                                        output_AX_ALG_data_V_1_sel_wr <= not(output_AX_ALG_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = output_AX_ALG_data_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_data_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_data_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_data_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_data_V_1_state)))) then 
                    output_AX_ALG_data_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = output_AX_ALG_data_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_data_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_data_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_data_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_data_V_1_state)))) then 
                    output_AX_ALG_data_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = output_AX_ALG_data_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_data_V_1_state)) or ((ap_const_logic_1 = output_AX_ALG_data_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_data_V_1_state)) or ((ap_const_lv2_3 = output_AX_ALG_data_V_1_state) and not(((ap_const_logic_1 = output_AX_ALG_data_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_data_V_1_ack_out))) and not(((ap_const_logic_0 = output_AX_ALG_data_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_data_V_1_ack_out)))))) then 
                    output_AX_ALG_data_V_1_state <= ap_const_lv2_3;
                else 
                    output_AX_ALG_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_dest_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_dest_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_dest_V_1_ack_out) and (ap_const_logic_1 = output_AX_ALG_dest_V_1_vld_out))) then 
                                        output_AX_ALG_dest_V_1_sel_rd <= not(output_AX_ALG_dest_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_dest_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_dest_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_dest_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_dest_V_1_ack_in))) then 
                                        output_AX_ALG_dest_V_1_sel_wr <= not(output_AX_ALG_dest_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_dest_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_dest_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = output_AX_ALG_dest_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_dest_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_dest_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_dest_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_dest_V_1_state)))) then 
                    output_AX_ALG_dest_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = output_AX_ALG_dest_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_dest_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_dest_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_dest_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_dest_V_1_state)))) then 
                    output_AX_ALG_dest_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = output_AX_ALG_dest_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_dest_V_1_state)) or ((ap_const_logic_1 = output_AX_ALG_dest_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_dest_V_1_state)) or ((ap_const_lv2_3 = output_AX_ALG_dest_V_1_state) and not(((ap_const_logic_1 = output_AX_ALG_dest_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_dest_V_1_ack_out))) and not(((ap_const_logic_0 = output_AX_ALG_dest_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_dest_V_1_ack_out)))))) then 
                    output_AX_ALG_dest_V_1_state <= ap_const_lv2_3;
                else 
                    output_AX_ALG_dest_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_id_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_id_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_id_V_1_ack_out) and (ap_const_logic_1 = output_AX_ALG_id_V_1_vld_out))) then 
                                        output_AX_ALG_id_V_1_sel_rd <= not(output_AX_ALG_id_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_id_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_id_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_id_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_id_V_1_ack_in))) then 
                                        output_AX_ALG_id_V_1_sel_wr <= not(output_AX_ALG_id_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_id_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_id_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = output_AX_ALG_id_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_id_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_id_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_id_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_id_V_1_state)))) then 
                    output_AX_ALG_id_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = output_AX_ALG_id_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_id_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_id_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_id_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_id_V_1_state)))) then 
                    output_AX_ALG_id_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = output_AX_ALG_id_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_id_V_1_state)) or ((ap_const_logic_1 = output_AX_ALG_id_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_id_V_1_state)) or ((ap_const_lv2_3 = output_AX_ALG_id_V_1_state) and not(((ap_const_logic_1 = output_AX_ALG_id_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_id_V_1_ack_out))) and not(((ap_const_logic_0 = output_AX_ALG_id_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_id_V_1_ack_out)))))) then 
                    output_AX_ALG_id_V_1_state <= ap_const_lv2_3;
                else 
                    output_AX_ALG_id_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_keep_V_1_ack_out) and (ap_const_logic_1 = output_AX_ALG_keep_V_1_vld_out))) then 
                                        output_AX_ALG_keep_V_1_sel_rd <= not(output_AX_ALG_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_keep_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_keep_V_1_ack_in))) then 
                                        output_AX_ALG_keep_V_1_sel_wr <= not(output_AX_ALG_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = output_AX_ALG_keep_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_keep_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_keep_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_keep_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_keep_V_1_state)))) then 
                    output_AX_ALG_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = output_AX_ALG_keep_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_keep_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_keep_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_keep_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_keep_V_1_state)))) then 
                    output_AX_ALG_keep_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = output_AX_ALG_keep_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_keep_V_1_state)) or ((ap_const_logic_1 = output_AX_ALG_keep_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_keep_V_1_state)) or ((ap_const_lv2_3 = output_AX_ALG_keep_V_1_state) and not(((ap_const_logic_1 = output_AX_ALG_keep_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_keep_V_1_ack_out))) and not(((ap_const_logic_0 = output_AX_ALG_keep_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_keep_V_1_ack_out)))))) then 
                    output_AX_ALG_keep_V_1_state <= ap_const_lv2_3;
                else 
                    output_AX_ALG_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_last_V_1_ack_out) and (ap_const_logic_1 = output_AX_ALG_last_V_1_vld_out))) then 
                                        output_AX_ALG_last_V_1_sel_rd <= not(output_AX_ALG_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_last_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_last_V_1_ack_in))) then 
                                        output_AX_ALG_last_V_1_sel_wr <= not(output_AX_ALG_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = output_AX_ALG_last_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_last_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_last_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_last_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_last_V_1_state)))) then 
                    output_AX_ALG_last_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = output_AX_ALG_last_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_last_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_last_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_last_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_last_V_1_state)))) then 
                    output_AX_ALG_last_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = output_AX_ALG_last_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_last_V_1_state)) or ((ap_const_logic_1 = output_AX_ALG_last_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_last_V_1_state)) or ((ap_const_lv2_3 = output_AX_ALG_last_V_1_state) and not(((ap_const_logic_1 = output_AX_ALG_last_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_last_V_1_ack_out))) and not(((ap_const_logic_0 = output_AX_ALG_last_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_last_V_1_ack_out)))))) then 
                    output_AX_ALG_last_V_1_state <= ap_const_lv2_3;
                else 
                    output_AX_ALG_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_strb_V_1_ack_out) and (ap_const_logic_1 = output_AX_ALG_strb_V_1_vld_out))) then 
                                        output_AX_ALG_strb_V_1_sel_rd <= not(output_AX_ALG_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_strb_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_strb_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_strb_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_strb_V_1_ack_in))) then 
                                        output_AX_ALG_strb_V_1_sel_wr <= not(output_AX_ALG_strb_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = output_AX_ALG_strb_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_strb_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_strb_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_strb_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_strb_V_1_state)))) then 
                    output_AX_ALG_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = output_AX_ALG_strb_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_strb_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_strb_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_strb_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_strb_V_1_state)))) then 
                    output_AX_ALG_strb_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = output_AX_ALG_strb_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_strb_V_1_state)) or ((ap_const_logic_1 = output_AX_ALG_strb_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_strb_V_1_state)) or ((ap_const_lv2_3 = output_AX_ALG_strb_V_1_state) and not(((ap_const_logic_1 = output_AX_ALG_strb_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_strb_V_1_ack_out))) and not(((ap_const_logic_0 = output_AX_ALG_strb_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_strb_V_1_ack_out)))))) then 
                    output_AX_ALG_strb_V_1_state <= ap_const_lv2_3;
                else 
                    output_AX_ALG_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_user_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_user_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_user_V_1_ack_out) and (ap_const_logic_1 = output_AX_ALG_user_V_1_vld_out))) then 
                                        output_AX_ALG_user_V_1_sel_rd <= not(output_AX_ALG_user_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_user_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_user_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = output_AX_ALG_user_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_user_V_1_ack_in))) then 
                                        output_AX_ALG_user_V_1_sel_wr <= not(output_AX_ALG_user_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_AX_ALG_user_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_AX_ALG_user_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = output_AX_ALG_user_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_user_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_user_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_user_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_user_V_1_state)))) then 
                    output_AX_ALG_user_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = output_AX_ALG_user_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_user_V_1_ack_out) and (ap_const_lv2_3 = output_AX_ALG_user_V_1_state)) or ((ap_const_logic_0 = output_AX_ALG_user_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_user_V_1_state)))) then 
                    output_AX_ALG_user_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = output_AX_ALG_user_V_1_vld_in) and (ap_const_lv2_2 = output_AX_ALG_user_V_1_state)) or ((ap_const_logic_1 = output_AX_ALG_user_V_1_ack_out) and (ap_const_lv2_1 = output_AX_ALG_user_V_1_state)) or ((ap_const_lv2_3 = output_AX_ALG_user_V_1_state) and not(((ap_const_logic_1 = output_AX_ALG_user_V_1_vld_in) and (ap_const_logic_0 = output_AX_ALG_user_V_1_ack_out))) and not(((ap_const_logic_0 = output_AX_ALG_user_V_1_vld_in) and (ap_const_logic_1 = output_AX_ALG_user_V_1_ack_out)))))) then 
                    output_AX_ALG_user_V_1_state <= ap_const_lv2_3;
                else 
                    output_AX_ALG_user_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_data_V_0_load_A)) then
                input_AX_ALG_data_V_0_payload_A <= input_AX_ALG_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_data_V_0_load_B)) then
                input_AX_ALG_data_V_0_payload_B <= input_AX_ALG_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_dest_V_0_load_A)) then
                input_AX_ALG_dest_V_0_payload_A <= input_AX_ALG_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_dest_V_0_load_B)) then
                input_AX_ALG_dest_V_0_payload_B <= input_AX_ALG_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_id_V_0_load_A)) then
                input_AX_ALG_id_V_0_payload_A <= input_AX_ALG_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_id_V_0_load_B)) then
                input_AX_ALG_id_V_0_payload_B <= input_AX_ALG_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_keep_V_0_load_A)) then
                input_AX_ALG_keep_V_0_payload_A <= input_AX_ALG_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_keep_V_0_load_B)) then
                input_AX_ALG_keep_V_0_payload_B <= input_AX_ALG_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_last_V_0_load_A)) then
                input_AX_ALG_last_V_0_payload_A <= input_AX_ALG_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_last_V_0_load_B)) then
                input_AX_ALG_last_V_0_payload_B <= input_AX_ALG_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_strb_V_0_load_A)) then
                input_AX_ALG_strb_V_0_payload_A <= input_AX_ALG_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_strb_V_0_load_B)) then
                input_AX_ALG_strb_V_0_payload_B <= input_AX_ALG_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_user_V_0_load_A)) then
                input_AX_ALG_user_V_0_payload_A <= input_AX_ALG_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = input_AX_ALG_user_V_0_load_B)) then
                input_AX_ALG_user_V_0_payload_B <= input_AX_ALG_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_data_V_1_load_A)) then
                output_AX_ALG_data_V_1_payload_A <= grp_write_data_fu_89_output_AX_ALG_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_data_V_1_load_B)) then
                output_AX_ALG_data_V_1_payload_B <= grp_write_data_fu_89_output_AX_ALG_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_dest_V_1_load_A)) then
                output_AX_ALG_dest_V_1_payload_A <= grp_write_data_fu_89_output_AX_ALG_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_dest_V_1_load_B)) then
                output_AX_ALG_dest_V_1_payload_B <= grp_write_data_fu_89_output_AX_ALG_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_id_V_1_load_A)) then
                output_AX_ALG_id_V_1_payload_A <= grp_write_data_fu_89_output_AX_ALG_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_id_V_1_load_B)) then
                output_AX_ALG_id_V_1_payload_B <= grp_write_data_fu_89_output_AX_ALG_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_keep_V_1_load_A)) then
                output_AX_ALG_keep_V_1_payload_A <= grp_write_data_fu_89_output_AX_ALG_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_keep_V_1_load_B)) then
                output_AX_ALG_keep_V_1_payload_B <= grp_write_data_fu_89_output_AX_ALG_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_last_V_1_load_A)) then
                output_AX_ALG_last_V_1_payload_A <= grp_write_data_fu_89_output_AX_ALG_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_last_V_1_load_B)) then
                output_AX_ALG_last_V_1_payload_B <= grp_write_data_fu_89_output_AX_ALG_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_strb_V_1_load_A)) then
                output_AX_ALG_strb_V_1_payload_A <= grp_write_data_fu_89_output_AX_ALG_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_strb_V_1_load_B)) then
                output_AX_ALG_strb_V_1_payload_B <= grp_write_data_fu_89_output_AX_ALG_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_user_V_1_load_A)) then
                output_AX_ALG_user_V_1_payload_A <= grp_write_data_fu_89_output_AX_ALG_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = output_AX_ALG_user_V_1_load_B)) then
                output_AX_ALG_user_V_1_payload_B <= grp_write_data_fu_89_output_AX_ALG_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n = ap_const_logic_1))) then
                p_Val2_1_reg_138 <= p_Val2_1_fu_127_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (output_AX_ALG_data_V_1_ack_in, output_AX_ALG_keep_V_1_ack_in, output_AX_ALG_strb_V_1_ack_in, output_AX_ALG_user_V_1_ack_in, output_AX_ALG_last_V_1_ack_in, output_AX_ALG_id_V_1_ack_in, output_AX_ALG_dest_V_1_ack_in, buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n, ap_CS_fsm, ap_CS_fsm_state2, grp_sweep_algorithm_DECM_fu_76_ap_done, grp_write_data_fu_89_ap_done, ap_CS_fsm_state3, tmp_s_fu_132_p2, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_sweep_algorithm_DECM_fu_76_ap_done = ap_const_logic_1) and (ap_const_lv1_0 = tmp_s_fu_132_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_sweep_algorithm_DECM_fu_76_ap_done = ap_const_logic_1) and (ap_const_lv1_1 = tmp_s_fu_132_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_write_data_fu_89_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and not(((ap_const_logic_0 = output_AX_ALG_data_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_keep_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_strb_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_user_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_last_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_id_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_dest_V_1_ack_in))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state5_assign_proc : process(output_AX_ALG_data_V_1_ack_in, output_AX_ALG_keep_V_1_ack_in, output_AX_ALG_strb_V_1_ack_in, output_AX_ALG_user_V_1_ack_in, output_AX_ALG_last_V_1_ack_in, output_AX_ALG_id_V_1_ack_in, output_AX_ALG_dest_V_1_ack_in)
    begin
                ap_block_state5 <= ((ap_const_logic_0 = output_AX_ALG_data_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_keep_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_strb_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_user_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_last_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_id_V_1_ack_in) or (ap_const_logic_0 = output_AX_ALG_dest_V_1_ack_in));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    buf_Tj_in_0_V_read_data_fu_109_ap_start_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_Tj_in_0_V_read_data_fu_109_ap_start <= ap_const_logic_1;
        else 
            buf_Tj_in_0_V_read_data_fu_109_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TVALID <= input_AX_ALG_dest_V_0_state(0);
    grp_sweep_algorithm_DECM_fu_76_ap_start <= ap_reg_grp_sweep_algorithm_DECM_fu_76_ap_start;
    grp_write_data_fu_89_ap_start <= ap_reg_grp_write_data_fu_89_ap_start;
    grp_write_data_fu_89_output_AX_ALG_TREADY <= output_AX_ALG_dest_V_1_state(1);

    input_AX_ALG_TDATA_blk_n_assign_proc : process(buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_AX_ALG_TDATA_blk_n <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TDATA_blk_n;
        else 
            input_AX_ALG_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_AX_ALG_TREADY <= input_AX_ALG_dest_V_0_state(1);
    input_AX_ALG_data_V_0_ack_in <= input_AX_ALG_data_V_0_state(1);
    input_AX_ALG_data_V_0_ack_out <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY;

    input_AX_ALG_data_V_0_data_out_assign_proc : process(input_AX_ALG_data_V_0_payload_A, input_AX_ALG_data_V_0_payload_B, input_AX_ALG_data_V_0_sel)
    begin
        if ((ap_const_logic_1 = input_AX_ALG_data_V_0_sel)) then 
            input_AX_ALG_data_V_0_data_out <= input_AX_ALG_data_V_0_payload_B;
        else 
            input_AX_ALG_data_V_0_data_out <= input_AX_ALG_data_V_0_payload_A;
        end if; 
    end process;

    input_AX_ALG_data_V_0_load_A <= (input_AX_ALG_data_V_0_state_cmp_full and not(input_AX_ALG_data_V_0_sel_wr));
    input_AX_ALG_data_V_0_load_B <= (input_AX_ALG_data_V_0_sel_wr and input_AX_ALG_data_V_0_state_cmp_full);
    input_AX_ALG_data_V_0_sel <= input_AX_ALG_data_V_0_sel_rd;
    input_AX_ALG_data_V_0_state_cmp_full <= '0' when (input_AX_ALG_data_V_0_state = ap_const_lv2_1) else '1';
    input_AX_ALG_data_V_0_vld_in <= input_AX_ALG_TVALID;
    input_AX_ALG_data_V_0_vld_out <= input_AX_ALG_data_V_0_state(0);
    input_AX_ALG_dest_V_0_ack_in <= input_AX_ALG_dest_V_0_state(1);
    input_AX_ALG_dest_V_0_ack_out <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY;

    input_AX_ALG_dest_V_0_data_out_assign_proc : process(input_AX_ALG_dest_V_0_payload_A, input_AX_ALG_dest_V_0_payload_B, input_AX_ALG_dest_V_0_sel)
    begin
        if ((ap_const_logic_1 = input_AX_ALG_dest_V_0_sel)) then 
            input_AX_ALG_dest_V_0_data_out <= input_AX_ALG_dest_V_0_payload_B;
        else 
            input_AX_ALG_dest_V_0_data_out <= input_AX_ALG_dest_V_0_payload_A;
        end if; 
    end process;

    input_AX_ALG_dest_V_0_load_A <= (input_AX_ALG_dest_V_0_state_cmp_full and not(input_AX_ALG_dest_V_0_sel_wr));
    input_AX_ALG_dest_V_0_load_B <= (input_AX_ALG_dest_V_0_sel_wr and input_AX_ALG_dest_V_0_state_cmp_full);
    input_AX_ALG_dest_V_0_sel <= input_AX_ALG_dest_V_0_sel_rd;
    input_AX_ALG_dest_V_0_state_cmp_full <= '0' when (input_AX_ALG_dest_V_0_state = ap_const_lv2_1) else '1';
    input_AX_ALG_dest_V_0_vld_in <= input_AX_ALG_TVALID;
    input_AX_ALG_dest_V_0_vld_out <= input_AX_ALG_dest_V_0_state(0);
    input_AX_ALG_id_V_0_ack_in <= input_AX_ALG_id_V_0_state(1);
    input_AX_ALG_id_V_0_ack_out <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY;

    input_AX_ALG_id_V_0_data_out_assign_proc : process(input_AX_ALG_id_V_0_payload_A, input_AX_ALG_id_V_0_payload_B, input_AX_ALG_id_V_0_sel)
    begin
        if ((ap_const_logic_1 = input_AX_ALG_id_V_0_sel)) then 
            input_AX_ALG_id_V_0_data_out <= input_AX_ALG_id_V_0_payload_B;
        else 
            input_AX_ALG_id_V_0_data_out <= input_AX_ALG_id_V_0_payload_A;
        end if; 
    end process;

    input_AX_ALG_id_V_0_load_A <= (input_AX_ALG_id_V_0_state_cmp_full and not(input_AX_ALG_id_V_0_sel_wr));
    input_AX_ALG_id_V_0_load_B <= (input_AX_ALG_id_V_0_sel_wr and input_AX_ALG_id_V_0_state_cmp_full);
    input_AX_ALG_id_V_0_sel <= input_AX_ALG_id_V_0_sel_rd;
    input_AX_ALG_id_V_0_state_cmp_full <= '0' when (input_AX_ALG_id_V_0_state = ap_const_lv2_1) else '1';
    input_AX_ALG_id_V_0_vld_in <= input_AX_ALG_TVALID;
    input_AX_ALG_id_V_0_vld_out <= input_AX_ALG_id_V_0_state(0);
    input_AX_ALG_keep_V_0_ack_in <= input_AX_ALG_keep_V_0_state(1);
    input_AX_ALG_keep_V_0_ack_out <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY;

    input_AX_ALG_keep_V_0_data_out_assign_proc : process(input_AX_ALG_keep_V_0_payload_A, input_AX_ALG_keep_V_0_payload_B, input_AX_ALG_keep_V_0_sel)
    begin
        if ((ap_const_logic_1 = input_AX_ALG_keep_V_0_sel)) then 
            input_AX_ALG_keep_V_0_data_out <= input_AX_ALG_keep_V_0_payload_B;
        else 
            input_AX_ALG_keep_V_0_data_out <= input_AX_ALG_keep_V_0_payload_A;
        end if; 
    end process;

    input_AX_ALG_keep_V_0_load_A <= (input_AX_ALG_keep_V_0_state_cmp_full and not(input_AX_ALG_keep_V_0_sel_wr));
    input_AX_ALG_keep_V_0_load_B <= (input_AX_ALG_keep_V_0_sel_wr and input_AX_ALG_keep_V_0_state_cmp_full);
    input_AX_ALG_keep_V_0_sel <= input_AX_ALG_keep_V_0_sel_rd;
    input_AX_ALG_keep_V_0_state_cmp_full <= '0' when (input_AX_ALG_keep_V_0_state = ap_const_lv2_1) else '1';
    input_AX_ALG_keep_V_0_vld_in <= input_AX_ALG_TVALID;
    input_AX_ALG_keep_V_0_vld_out <= input_AX_ALG_keep_V_0_state(0);
    input_AX_ALG_last_V_0_ack_in <= input_AX_ALG_last_V_0_state(1);
    input_AX_ALG_last_V_0_ack_out <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY;

    input_AX_ALG_last_V_0_data_out_assign_proc : process(input_AX_ALG_last_V_0_payload_A, input_AX_ALG_last_V_0_payload_B, input_AX_ALG_last_V_0_sel)
    begin
        if ((ap_const_logic_1 = input_AX_ALG_last_V_0_sel)) then 
            input_AX_ALG_last_V_0_data_out <= input_AX_ALG_last_V_0_payload_B;
        else 
            input_AX_ALG_last_V_0_data_out <= input_AX_ALG_last_V_0_payload_A;
        end if; 
    end process;

    input_AX_ALG_last_V_0_load_A <= (input_AX_ALG_last_V_0_state_cmp_full and not(input_AX_ALG_last_V_0_sel_wr));
    input_AX_ALG_last_V_0_load_B <= (input_AX_ALG_last_V_0_sel_wr and input_AX_ALG_last_V_0_state_cmp_full);
    input_AX_ALG_last_V_0_sel <= input_AX_ALG_last_V_0_sel_rd;
    input_AX_ALG_last_V_0_state_cmp_full <= '0' when (input_AX_ALG_last_V_0_state = ap_const_lv2_1) else '1';
    input_AX_ALG_last_V_0_vld_in <= input_AX_ALG_TVALID;
    input_AX_ALG_last_V_0_vld_out <= input_AX_ALG_last_V_0_state(0);
    input_AX_ALG_strb_V_0_ack_in <= input_AX_ALG_strb_V_0_state(1);
    input_AX_ALG_strb_V_0_ack_out <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY;

    input_AX_ALG_strb_V_0_data_out_assign_proc : process(input_AX_ALG_strb_V_0_payload_A, input_AX_ALG_strb_V_0_payload_B, input_AX_ALG_strb_V_0_sel)
    begin
        if ((ap_const_logic_1 = input_AX_ALG_strb_V_0_sel)) then 
            input_AX_ALG_strb_V_0_data_out <= input_AX_ALG_strb_V_0_payload_B;
        else 
            input_AX_ALG_strb_V_0_data_out <= input_AX_ALG_strb_V_0_payload_A;
        end if; 
    end process;

    input_AX_ALG_strb_V_0_load_A <= (input_AX_ALG_strb_V_0_state_cmp_full and not(input_AX_ALG_strb_V_0_sel_wr));
    input_AX_ALG_strb_V_0_load_B <= (input_AX_ALG_strb_V_0_sel_wr and input_AX_ALG_strb_V_0_state_cmp_full);
    input_AX_ALG_strb_V_0_sel <= input_AX_ALG_strb_V_0_sel_rd;
    input_AX_ALG_strb_V_0_state_cmp_full <= '0' when (input_AX_ALG_strb_V_0_state = ap_const_lv2_1) else '1';
    input_AX_ALG_strb_V_0_vld_in <= input_AX_ALG_TVALID;
    input_AX_ALG_strb_V_0_vld_out <= input_AX_ALG_strb_V_0_state(0);
    input_AX_ALG_user_V_0_ack_in <= input_AX_ALG_user_V_0_state(1);
    input_AX_ALG_user_V_0_ack_out <= buf_Tj_in_0_V_read_data_fu_109_input_AX_ALG_TREADY;

    input_AX_ALG_user_V_0_data_out_assign_proc : process(input_AX_ALG_user_V_0_payload_A, input_AX_ALG_user_V_0_payload_B, input_AX_ALG_user_V_0_sel)
    begin
        if ((ap_const_logic_1 = input_AX_ALG_user_V_0_sel)) then 
            input_AX_ALG_user_V_0_data_out <= input_AX_ALG_user_V_0_payload_B;
        else 
            input_AX_ALG_user_V_0_data_out <= input_AX_ALG_user_V_0_payload_A;
        end if; 
    end process;

    input_AX_ALG_user_V_0_load_A <= (input_AX_ALG_user_V_0_state_cmp_full and not(input_AX_ALG_user_V_0_sel_wr));
    input_AX_ALG_user_V_0_load_B <= (input_AX_ALG_user_V_0_sel_wr and input_AX_ALG_user_V_0_state_cmp_full);
    input_AX_ALG_user_V_0_sel <= input_AX_ALG_user_V_0_sel_rd;
    input_AX_ALG_user_V_0_state_cmp_full <= '0' when (input_AX_ALG_user_V_0_state = ap_const_lv2_1) else '1';
    input_AX_ALG_user_V_0_vld_in <= input_AX_ALG_TVALID;
    input_AX_ALG_user_V_0_vld_out <= input_AX_ALG_user_V_0_state(0);
    output_AX_ALG_TDATA <= output_AX_ALG_data_V_1_data_out;
    output_AX_ALG_TDEST <= output_AX_ALG_dest_V_1_data_out;
    output_AX_ALG_TID <= output_AX_ALG_id_V_1_data_out;
    output_AX_ALG_TKEEP <= output_AX_ALG_keep_V_1_data_out;
    output_AX_ALG_TLAST <= output_AX_ALG_last_V_1_data_out;
    output_AX_ALG_TSTRB <= output_AX_ALG_strb_V_1_data_out;
    output_AX_ALG_TUSER <= output_AX_ALG_user_V_1_data_out;
    output_AX_ALG_TVALID <= output_AX_ALG_dest_V_1_state(0);
    output_AX_ALG_data_V_1_ack_in <= output_AX_ALG_data_V_1_state(1);
    output_AX_ALG_data_V_1_ack_out <= output_AX_ALG_TREADY;

    output_AX_ALG_data_V_1_data_out_assign_proc : process(output_AX_ALG_data_V_1_payload_A, output_AX_ALG_data_V_1_payload_B, output_AX_ALG_data_V_1_sel)
    begin
        if ((ap_const_logic_1 = output_AX_ALG_data_V_1_sel)) then 
            output_AX_ALG_data_V_1_data_out <= output_AX_ALG_data_V_1_payload_B;
        else 
            output_AX_ALG_data_V_1_data_out <= output_AX_ALG_data_V_1_payload_A;
        end if; 
    end process;

    output_AX_ALG_data_V_1_load_A <= (output_AX_ALG_data_V_1_state_cmp_full and not(output_AX_ALG_data_V_1_sel_wr));
    output_AX_ALG_data_V_1_load_B <= (output_AX_ALG_data_V_1_sel_wr and output_AX_ALG_data_V_1_state_cmp_full);
    output_AX_ALG_data_V_1_sel <= output_AX_ALG_data_V_1_sel_rd;
    output_AX_ALG_data_V_1_state_cmp_full <= '0' when (output_AX_ALG_data_V_1_state = ap_const_lv2_1) else '1';
    output_AX_ALG_data_V_1_vld_in <= grp_write_data_fu_89_output_AX_ALG_TVALID;
    output_AX_ALG_data_V_1_vld_out <= output_AX_ALG_data_V_1_state(0);
    output_AX_ALG_dest_V_1_ack_in <= output_AX_ALG_dest_V_1_state(1);
    output_AX_ALG_dest_V_1_ack_out <= output_AX_ALG_TREADY;

    output_AX_ALG_dest_V_1_data_out_assign_proc : process(output_AX_ALG_dest_V_1_payload_A, output_AX_ALG_dest_V_1_payload_B, output_AX_ALG_dest_V_1_sel)
    begin
        if ((ap_const_logic_1 = output_AX_ALG_dest_V_1_sel)) then 
            output_AX_ALG_dest_V_1_data_out <= output_AX_ALG_dest_V_1_payload_B;
        else 
            output_AX_ALG_dest_V_1_data_out <= output_AX_ALG_dest_V_1_payload_A;
        end if; 
    end process;

    output_AX_ALG_dest_V_1_load_A <= (output_AX_ALG_dest_V_1_state_cmp_full and not(output_AX_ALG_dest_V_1_sel_wr));
    output_AX_ALG_dest_V_1_load_B <= (output_AX_ALG_dest_V_1_sel_wr and output_AX_ALG_dest_V_1_state_cmp_full);
    output_AX_ALG_dest_V_1_sel <= output_AX_ALG_dest_V_1_sel_rd;
    output_AX_ALG_dest_V_1_state_cmp_full <= '0' when (output_AX_ALG_dest_V_1_state = ap_const_lv2_1) else '1';
    output_AX_ALG_dest_V_1_vld_in <= grp_write_data_fu_89_output_AX_ALG_TVALID;
    output_AX_ALG_dest_V_1_vld_out <= output_AX_ALG_dest_V_1_state(0);
    output_AX_ALG_id_V_1_ack_in <= output_AX_ALG_id_V_1_state(1);
    output_AX_ALG_id_V_1_ack_out <= output_AX_ALG_TREADY;

    output_AX_ALG_id_V_1_data_out_assign_proc : process(output_AX_ALG_id_V_1_payload_A, output_AX_ALG_id_V_1_payload_B, output_AX_ALG_id_V_1_sel)
    begin
        if ((ap_const_logic_1 = output_AX_ALG_id_V_1_sel)) then 
            output_AX_ALG_id_V_1_data_out <= output_AX_ALG_id_V_1_payload_B;
        else 
            output_AX_ALG_id_V_1_data_out <= output_AX_ALG_id_V_1_payload_A;
        end if; 
    end process;

    output_AX_ALG_id_V_1_load_A <= (output_AX_ALG_id_V_1_state_cmp_full and not(output_AX_ALG_id_V_1_sel_wr));
    output_AX_ALG_id_V_1_load_B <= (output_AX_ALG_id_V_1_sel_wr and output_AX_ALG_id_V_1_state_cmp_full);
    output_AX_ALG_id_V_1_sel <= output_AX_ALG_id_V_1_sel_rd;
    output_AX_ALG_id_V_1_state_cmp_full <= '0' when (output_AX_ALG_id_V_1_state = ap_const_lv2_1) else '1';
    output_AX_ALG_id_V_1_vld_in <= grp_write_data_fu_89_output_AX_ALG_TVALID;
    output_AX_ALG_id_V_1_vld_out <= output_AX_ALG_id_V_1_state(0);
    output_AX_ALG_keep_V_1_ack_in <= output_AX_ALG_keep_V_1_state(1);
    output_AX_ALG_keep_V_1_ack_out <= output_AX_ALG_TREADY;

    output_AX_ALG_keep_V_1_data_out_assign_proc : process(output_AX_ALG_keep_V_1_payload_A, output_AX_ALG_keep_V_1_payload_B, output_AX_ALG_keep_V_1_sel)
    begin
        if ((ap_const_logic_1 = output_AX_ALG_keep_V_1_sel)) then 
            output_AX_ALG_keep_V_1_data_out <= output_AX_ALG_keep_V_1_payload_B;
        else 
            output_AX_ALG_keep_V_1_data_out <= output_AX_ALG_keep_V_1_payload_A;
        end if; 
    end process;

    output_AX_ALG_keep_V_1_load_A <= (output_AX_ALG_keep_V_1_state_cmp_full and not(output_AX_ALG_keep_V_1_sel_wr));
    output_AX_ALG_keep_V_1_load_B <= (output_AX_ALG_keep_V_1_sel_wr and output_AX_ALG_keep_V_1_state_cmp_full);
    output_AX_ALG_keep_V_1_sel <= output_AX_ALG_keep_V_1_sel_rd;
    output_AX_ALG_keep_V_1_state_cmp_full <= '0' when (output_AX_ALG_keep_V_1_state = ap_const_lv2_1) else '1';
    output_AX_ALG_keep_V_1_vld_in <= grp_write_data_fu_89_output_AX_ALG_TVALID;
    output_AX_ALG_keep_V_1_vld_out <= output_AX_ALG_keep_V_1_state(0);
    output_AX_ALG_last_V_1_ack_in <= output_AX_ALG_last_V_1_state(1);
    output_AX_ALG_last_V_1_ack_out <= output_AX_ALG_TREADY;

    output_AX_ALG_last_V_1_data_out_assign_proc : process(output_AX_ALG_last_V_1_payload_A, output_AX_ALG_last_V_1_payload_B, output_AX_ALG_last_V_1_sel)
    begin
        if ((ap_const_logic_1 = output_AX_ALG_last_V_1_sel)) then 
            output_AX_ALG_last_V_1_data_out <= output_AX_ALG_last_V_1_payload_B;
        else 
            output_AX_ALG_last_V_1_data_out <= output_AX_ALG_last_V_1_payload_A;
        end if; 
    end process;

    output_AX_ALG_last_V_1_load_A <= (output_AX_ALG_last_V_1_state_cmp_full and not(output_AX_ALG_last_V_1_sel_wr));
    output_AX_ALG_last_V_1_load_B <= (output_AX_ALG_last_V_1_sel_wr and output_AX_ALG_last_V_1_state_cmp_full);
    output_AX_ALG_last_V_1_sel <= output_AX_ALG_last_V_1_sel_rd;
    output_AX_ALG_last_V_1_state_cmp_full <= '0' when (output_AX_ALG_last_V_1_state = ap_const_lv2_1) else '1';
    output_AX_ALG_last_V_1_vld_in <= grp_write_data_fu_89_output_AX_ALG_TVALID;
    output_AX_ALG_last_V_1_vld_out <= output_AX_ALG_last_V_1_state(0);
    output_AX_ALG_strb_V_1_ack_in <= output_AX_ALG_strb_V_1_state(1);
    output_AX_ALG_strb_V_1_ack_out <= output_AX_ALG_TREADY;

    output_AX_ALG_strb_V_1_data_out_assign_proc : process(output_AX_ALG_strb_V_1_payload_A, output_AX_ALG_strb_V_1_payload_B, output_AX_ALG_strb_V_1_sel)
    begin
        if ((ap_const_logic_1 = output_AX_ALG_strb_V_1_sel)) then 
            output_AX_ALG_strb_V_1_data_out <= output_AX_ALG_strb_V_1_payload_B;
        else 
            output_AX_ALG_strb_V_1_data_out <= output_AX_ALG_strb_V_1_payload_A;
        end if; 
    end process;

    output_AX_ALG_strb_V_1_load_A <= (output_AX_ALG_strb_V_1_state_cmp_full and not(output_AX_ALG_strb_V_1_sel_wr));
    output_AX_ALG_strb_V_1_load_B <= (output_AX_ALG_strb_V_1_sel_wr and output_AX_ALG_strb_V_1_state_cmp_full);
    output_AX_ALG_strb_V_1_sel <= output_AX_ALG_strb_V_1_sel_rd;
    output_AX_ALG_strb_V_1_state_cmp_full <= '0' when (output_AX_ALG_strb_V_1_state = ap_const_lv2_1) else '1';
    output_AX_ALG_strb_V_1_vld_in <= grp_write_data_fu_89_output_AX_ALG_TVALID;
    output_AX_ALG_strb_V_1_vld_out <= output_AX_ALG_strb_V_1_state(0);
    output_AX_ALG_user_V_1_ack_in <= output_AX_ALG_user_V_1_state(1);
    output_AX_ALG_user_V_1_ack_out <= output_AX_ALG_TREADY;

    output_AX_ALG_user_V_1_data_out_assign_proc : process(output_AX_ALG_user_V_1_payload_A, output_AX_ALG_user_V_1_payload_B, output_AX_ALG_user_V_1_sel)
    begin
        if ((ap_const_logic_1 = output_AX_ALG_user_V_1_sel)) then 
            output_AX_ALG_user_V_1_data_out <= output_AX_ALG_user_V_1_payload_B;
        else 
            output_AX_ALG_user_V_1_data_out <= output_AX_ALG_user_V_1_payload_A;
        end if; 
    end process;

    output_AX_ALG_user_V_1_load_A <= (output_AX_ALG_user_V_1_state_cmp_full and not(output_AX_ALG_user_V_1_sel_wr));
    output_AX_ALG_user_V_1_load_B <= (output_AX_ALG_user_V_1_sel_wr and output_AX_ALG_user_V_1_state_cmp_full);
    output_AX_ALG_user_V_1_sel <= output_AX_ALG_user_V_1_sel_rd;
    output_AX_ALG_user_V_1_state_cmp_full <= '0' when (output_AX_ALG_user_V_1_state = ap_const_lv2_1) else '1';
    output_AX_ALG_user_V_1_vld_in <= grp_write_data_fu_89_output_AX_ALG_TVALID;
    output_AX_ALG_user_V_1_vld_out <= output_AX_ALG_user_V_1_state(0);
    p_Val2_1_fu_127_p1 <= buf_Tj_in_0_V_read_data_fu_109_ap_return(24 - 1 downto 0);
    tmp_s_fu_132_p2 <= "1" when (full_fifo = ap_const_lv32_0) else "0";
end behav;
